#ifndef APO_SEM_CONST_H
#define APO_SEM_CONST_H

// general constants
#define WORLD_WIDTH 1600
#define WORLD_HEIGHT 1200

// colors
#define RED 0XF800
#define GREEN 0X07E0
#define GRAY 0X9CF3
#define WHITE 0XFFFF
#define YELLOW 0XFFE0

// projectile constants
#define MAX_PROJECTILE_COUNT 50
#define PROJECTILE_COLOR YELLOW
#define PROJECTILE_SPEED 30
#define PROJECTILE_WIDTH 4
#define PROJECTILE_HEIGHT 10

// player constants
#define PLAYER_COLOR GREEN
#define PLAYER_WIDTH 16
#define PLAYER_HEIGHT 32
#define PLAYER_START_MAX_HEALTH 100
#define PLAYER_START_DAMAGE 10
#define PLAYER_START_FIRE_COOLDOWN 2.0f
#define PLAYER_MAX_SPEED 20
#define PLAYER_ACCELERATION_MOD 500.00f
#define PLAYER_SCORE_GAIN 10
#define PLAYER_INVINCIBLE_GAIN 80
#define PLAYER_STUN_GAIN 10
#define PLAYER_KNOCKBACK_GAIN 150
#define PLAYER_KNOCKBACK_FRICTION 0.6F
#define PLAYER_BASE_XP_NEEDED 30
#define PLAYER_NEEDED_XP_GAIN 30

// enemy constants
#define MAX_ENEMY_COUNT 50
#define ENEMY_COLOR RED
#define ENEMY_SPEED 25
#define ENEMY_SPAWN_HEALTH 100
#define ENEMY_WIDTH 12
#define ENEMY_HEIGHT 24
#define ENEMY_DAMAGE 10
#define ENEMY_KNOCKBACK_GAIN 80
#define ENEMY_KNOCKBACK_FRICTION 0.3f
#define ENEMY_STUN_GAIN 20
#define ENEMY_INTRO_SPAWN_TIME 30.0f
#define ENEMY_INTRO_SPAWN_COOLDOWN 8.0f
#define ENEMY_SPAWN_COOL_MAX 8.0f
#define ENEMY_SPAWN_COOL_MIN 1.5f
#define ENEMY_SPAWN_COOL_DECAY 0.004f
#define ENEMY_HEALTH_SCALING_FACTOR 5.0f
#define ENEMY_DAMAGE_SCALING_FACTOR 2.0f

// camera constants
#define CAMERA_CONVERGENCE_RATE 2

// UI constants
//  health bar parameters
#define HEALTH_BAR_X 3
#define HEALTH_BAR_Y 5
#define HEALTH_BAR_WIDTH 100
#define HEALTH_BAR_HEIGHT 30
#define HEALTH_BAR_ENDX (HEALTH_BAR_X + HEALTH_BAR_WIDTH)
#define HEALTH_BAR_ENDY (HEALTH_BAR_Y + HEALTH_BAR_HEIGHT)
#define HEALTH_BAR_SPACING 4

#define HEALTH_BAR_BACKGROUND GRAY
#define HEALTH_BAR_FOREGROUND_ONE RED
#define HEALTH_BAR_FOREGROUND_TWO GREEN

// score counter parameters
#define SCORE_X (SCREEN_WIDTH / 2 - 100)
#define SCORE_Y 5
#define SCORE_DIGITS 10
#define SCORE_TEXT "Score: "
#define SCORE_CHARS (strlen(SCORE_TEXT))
#define SCORE_TEXT_LENGTH (SCORE_DIGITS + SCORE_CHARS + 1)

// required score counter parameters
#define REQUIRED_SCORE_X (SCORE_X + 90)
#define REQUIRED_SCORE_Y SCORE_Y
#define REQUIRED_SCORE_DIGITS SCORE_DIGITS
#define REQUIRED_SCORE_TEXT "Next level: "
#define REQUIRED_SCORE_CHARS (strlen(REQUIRED_SCORE_TEXT))
#define REQUIRED_SCORE_TEXT_LENGTH (REQUIRED_SCORE_DIGITS + REQUIRED_SCORE_CHARS + 1)

// define death menu score counter
#define DEATH_SCORE_DIGITS 10
#define DEATH_SCORE_TEXT "Final Score: "
#define DEATH_SCORE_CHARS (strlen(DEATH_SCORE_TEXT))
#define DEATH_SCORE_TEXT_LENGTH (SCORE_DIGITS + SCORE_CHARS + 1)

// active abilities constants
#define ACTIVE_ABIlITY_COUNT 2

#endif // APO_SEM_CONST_H
